# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "it-gro/ubuntu-20-04-srv-lvm"
    
    config.vm.box_check_update = false
  
    config.vm.define     "lxadmpro-hw08-lvm"
    config.vm.hostname = "lxadmpro-hw08-lvm"
    config.vm.network    "public_network", 
                 bridge: "Intel(R) Dual Band Wireless-AC 8265", 
                    ip: "192.168.0.148"
  
    config.vm.provider "virtualbox" do |vb|
      vb.name   = "lxadmpro-hw08-lvm"
      vb.gui    = true
      vb.memory = 1024
      vb.cpus   = 2
    end
    
    config.vm.synced_folder "./data", "/vagrant", automount: true
  
    config.vm.provision "file", source: "./keys/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    public_key = File.readlines("./keys/id_rsa.pub").first.strip
  
    config.vm.provision "shell", inline: <<-SHELL
  
      echo #{public_key} >> /home/vagrant/.ssh/authorized_keys
      chmod -R 600 /home/vagrant/.ssh/authorized_keys

      sudo locale-gen en_US.UTF-8
      sudo update-locale LANG=en_US.UTF-8

      L='us' && sudo sed -i 's/XKBLAYOUT=\"\w*"/XKBLAYOUT=\"'$L'\"/g' /etc/default/keyboard

      # set Timezone
      timedatectl set-timezone Europe/Moscow

      sudo sysctl -w kernel.printk="2 4 1 7"

    SHELL
  end
  